"""
Ticket D4: Singleton Detector
=========================================================

Filters out weak clusters generated by D3. If the best direct S1-Cand score
in a resolved cluster is below a learned threshold, the S1 is declared a singleton
(meaning it has no true matches) and the cluster is dropped to protect Precision.

Inputs:
  scores/path_d3_resolved.parquet
  scores/path_d1_val.parquet
Outputs:
  scores/path_d4_final.parquet
"""

import argparse
import time
from collections import defaultdict
from pathlib import Path

import numpy as np
import pandas as pd
from tqdm import tqdm

from src.common.data_loader import load_all_sources
from eval.f05 import macro_f05


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--d3-preds", type=Path, default="scores/path_d3_resolved.parquet")
    parser.add_argument("--d1-scores", type=Path, default="scores/path_d1_val.parquet")
    parser.add_argument("--out", type=Path, default="scores/path_d4_final.parquet")
    args = parser.parse_args()

    t_start = time.time()
    print("=" * 60)
    print("D4: SINGLETON DETECTOR (PRUNING)")
    print("=" * 60)

    # 1. Load Data
    print(f"\n[Load] Reading D3 predictions from {args.d3_preds}...")
    d3_df = pd.read_parquet(args.d3_preds)
    
    print(f"[Load] Reading D1 scores from {args.d1_scores}...")
    d1_df = pd.read_parquet(args.d1_scores)

    # Group D3 into dict: s1_id -> list of cand_id
    print("  Mapping clusters...")
    d3_preds = d3_df.groupby('s1_id')['cand_id'].apply(list).to_dict()
    
    # Map D1 scores for O(1) lookup
    print("  Mapping D1 pairwise scores...")
    # Using a nested dict or tuple keys. Tuple keys is easier.
    score_map = dict(zip(zip(d1_df.s1_id, d1_df.cand_id), d1_df.score))
    
    # Load GT for eval
    _, _, _, gt = load_all_sources()
    val_s1_ids = set(gt['source1_entity_id'].unique())
    
    gt_dict = {}
    for _, row in gt.iterrows():
        if row['source1_entity_id'] in val_s1_ids:
            gt_dict[row['source1_entity_id']] = row['matches']

    # 2. Compute Max Score per Cluster
    print("\n[Analyze] Computing maximum edge score for each S1 cluster...")
    cluster_max_scores = {}
    for s1_id, cands in tqdm(d3_preds.items(), desc="  Clusters"):
        if not cands:
            cluster_max_scores[s1_id] = 0.0
            continue
            
        best_score = 0.0
        for cand in cands:
            score = score_map.get((s1_id, cand), 0.0)
            if score > best_score:
                best_score = score
        cluster_max_scores[s1_id] = best_score
        
    # 3. Threshold Sweep
    print("\n[Sweep] Evaluating Singleton Thresholds...")
    best_thresh, best_f05 = 0.0, 0.0
    
    for thresh in np.arange(0.0, 1.0, 0.05):
        # Apply threshold: keep if max_score >= thresh, else []
        thresh_preds = {sid: [] for sid in val_s1_ids}
        
        for s1_id, cands in d3_preds.items():
            if s1_id not in val_s1_ids:
                continue
            if cluster_max_scores.get(s1_id, 0.0) >= thresh:
                thresh_preds[s1_id] = cands
                
        f05 = macro_f05(thresh_preds, gt_dict)
        if f05 > best_f05:
            best_f05, best_thresh = f05, thresh
            
    print(f"\n[Result] Best Val Macro F0.5 : {best_f05:.5f} (Singleton Threshold = {best_thresh:.2f})")
    
    # 4. Save Final
    print(f"\n[Save] Generating final output at threshold {best_thresh:.2f}...")
    final_rows = []
    for s1_id, cands in d3_preds.items():
        if cluster_max_scores.get(s1_id, 0.0) >= best_thresh:
            for cand in cands:
                final_rows.append({'s1_id': s1_id, 'cand_id': cand})
                
    final_df = pd.DataFrame(final_rows) if final_rows else pd.DataFrame(columns=['s1_id', 'cand_id'])
    args.out.parent.mkdir(exist_ok=True, parents=True)
    final_df.to_parquet(args.out, index=False)
    
    print(f"  Saved {len(final_df):,} retained edges.")
    
    print(f"\n{'='*60}")
    print(f"D4 complete in {time.time()-t_start:.1f}s")
    print(f"{'='*60}")


if __name__ == "__main__":
    main()
