"""
Ticket A3: Negative Sampling
Samples hard negatives from the blocking stage to create a balanced
training set for the Path A classical ML classifier (LightGBM/XGBoost).
Since candidates were generated by blocking rules (TF-IDF, Token overlap, etc.),
all negatives here are "hard" negatives.
"""

import argparse
from pathlib import Path
import pandas as pd
import numpy as np

def main():
    parser = argparse.ArgumentParser(description="A3 Negative Sampling")
    parser.add_argument("--features", type=Path, default="output/a2_features.parquet", help="Path to feature table")
    parser.add_argument("--out", type=Path, default="output/a3_train_sampled.parquet", help="Path to save sampled training data")
    parser.add_argument("--ratio", type=float, default=3.0, help="Ratio of negatives to positives")
    parser.add_argument("--seed", type=int, default=42, help="Random seed for sampling")
    args = parser.parse_args()

    if not args.features.exists():
        print(f"Error: {args.features} not found. Please run A2 features first.")
        return

    print(f"Loading feature table from {args.features}...")
    df = pd.read_parquet(args.features)

    if 'is_match' not in df.columns:
        print("Error: 'is_match' column not found in features. Ensure ground truth was merged in A2.")
        return

    positives = df[df['is_match'] == 1]
    negatives = df[df['is_match'] == 0]

    num_pos = len(positives)
    num_neg = len(negatives)
    target_neg = int(num_pos * args.ratio)

    print("=" * 50)
    print("BEFORE SAMPLING (Class Balance):")
    print(f"  Positives (Matches): {num_pos:,}")
    print(f"  Negatives (Hard Confusers): {num_neg:,}")
    if num_pos > 0:
        print(f"  Ratio: 1 : {num_neg / num_pos:.1f}")
    else:
        print("  Ratio: N/A (0 positives)")
    print("=" * 50)

    if num_pos == 0:
        print("Warning: No positive pairs found. Sampling cannot proceed properly.")
        sampled_negatives = negatives
    else:
        if num_neg > target_neg:
            print(f"Downsampling negatives to {target_neg:,} (ratio 1:{args.ratio})...")
            sampled_negatives = negatives.sample(n=target_neg, random_state=args.seed)
        else:
            print(f"Number of negatives ({num_neg:,}) is already below target ({target_neg:,}). Keeping all.")
            sampled_negatives = negatives

    train_sampled = pd.concat([positives, sampled_negatives]).sample(frac=1.0, random_state=args.seed).reset_index(drop=True)

    print("\n" + "=" * 50)
    print("AFTER SAMPLING (Final Training Set):")
    print(f"  Total Pairs: {len(train_sampled):,}")
    print(f"  Positives: {len(train_sampled[train_sampled['is_match'] == 1]):,}")
    print(f"  Negatives: {len(train_sampled[train_sampled['is_match'] == 0]):,}")
    print("=" * 50)

    args.out.parent.mkdir(exist_ok=True, parents=True)
    train_sampled.to_parquet(args.out, index=False)
    print(f"\nSaved sampled training dataset to {args.out}")

if __name__ == "__main__":
    main()
